### ISSUE TITLE
Luakit July 2017 release

### ISSUE THREAD

**Issue by aidanholm** [luakit/luakit#324]
Todo:

- [x] Make (rather lengthy) changelog
- [x] Finish backwards-incompatible API changes:
  - [x] async webview source API: https://github.com/aidanholm/luakit/issues/353
  - ~~async `eval_js` API~~: this one can wait
- [x] Remove everything currently deprecated
   - [x] Remove domain_props.user_stylesheet_uri
   - [x] Remove styles-rewrite-old-files
   - [x] Remove non-functional mixed_content module
- [x] Update website mentions to luakit.org
- [x] Set sensible default process limit
- [x] Fix blocking issues
   - [x] Segfault on download cancel: https://github.com/aidanholm/luakit/issues/402
   - [x] #328 Async APIs
   - [x] #335 Documentation generation
   - [x] https://github.com/aidanholm/luakit/issues/404 Error page issues on non-English locale
   - [x] #340 Incomplete documentation

**Comment by aidanholm** [comment]
Done at 5bdc45fa!

**Comment by xkpd3** [comment]
Big congratulations for your first luakit release!!!! :1st_place_medal:
