### ISSUE TITLE
Add pinned/fixed tabs module

### ISSUE THREAD

**Issue by aidanholm** [luakit/luakit#338]
Requested by @szbnwer at https://github.com/luakit/luakit/issues/325#issuecomment-313868301

**Comment by aidanholm** [comment]
### Problems
- It's unclear where the pinned "state" should be stored; it's not webview-specific and it's not really specific to a tab widget
  - Could convert `config/webview.lua` to a `tabview.lua` module, and store it there.
- ~It's unclear how pinned tabs should interact with session saving and restoring.~
### Todo
- [x] tablist: don't assume tabs are all the same size
- [ ] tablist: move max_width property to tab
- [x] tab: add ability to override label_format

**Comment by hippi777** [comment]
if you mean under multi session more than one window, then it can be simply on the first opened window, or a simple option could say if something should be accessed from every instances; if it's multi user/setup thing, then i think a single user/setup can have it's own set, and i think shared components can be made, but i'm still not in the depths of codes to know...

and if it's possible to make it iconic (without title) in horizontal view, then that's good, because i have a billion opened tabs always :D i still didn't even check out how that seems in luakit currently... and that could be a simple option as well for any site, like there are a lotsa sites where i know well everything from an icon, so i can save space...

**Comment by aidanholm** [comment]
By multi-session, I mean the ability to have multiple saved sessions: you could have a work session, a personal session, sessions for projects, etc. Part of the idea of pinned tabs is that they open automatically, even if you start a new session. It's not easy to reconcile that with multiple sessions:

- with multiple sessions, each session has to have its own set of pinned tabs
- therefore, when starting a new blank session, we never load pinned tabs (a blank session doesn't have any yet)

Multiple sessions aren't supported yet, but there was talk about it.

**Comment by aidanholm** [comment]
To clarify: pinned tabs roll up a bunch of concepts into one:

 1. They persist across sessions: in e.g. firefox, you open up a new session and your pinned tabs start open.
 2. They're small and they stick to one side of the tab bar: this is mostly just cosmetic and easy to do. 
 3. They prevent you from closing the tab accidentally: also easy.

Re 1), If you have sessions, why would you need pinned tabs at all? Sessions already save things for next time. If you want a set of sites to start open in new sessions, that's easy too.

So with that in mind, I think the only reasonable way that luakit pinned tabs could work is to do 2) and 3), and leave 1) to the session system. Separation of concerns, and all that. Thoughts?

**Comment by hippi777** [comment]
sounds great, how would these be initialized? like luakit -s profile or something like that?

**Comment by hippi777** [comment]
possibly with vertical tabs the iconic tabs could fill up rows to save space, but everything is fine as you are saying it :)

i'm feeling the need more and more to finally migrate my stuffs to luakit asap just i have so few free time and i wanna learn much more before that, but i'm already spreading the verb that luakit is such a great matery out there :D

**Comment by aidanholm** [comment]
- There'll be a lua module that you load in `rc.lua`, probably called `pinned_tabs.lua`.
- There'll be some default binds provided by that module for pinning and unpinning a tab.
- You start out with no pinned tabs. You `:open` a URL, and then press `tp` or something to toggle whether it's pinned.

I think filling up rows could be good to save space, but it could look weird if you resize the vertical tab bar.
Thanks for promoting ;)

**Comment by hippi777** [comment]
why could it look weird? it can be justified or there can be a bit homogene space next to it in case of size not matching, and when it's actually resized, then it can be reordered (if that is possible in runtime)

**Comment by aidanholm** [comment]
There's a few different ways they could be wrapped; but the best way is to try it and see what looks best of course. Yep, that's possible.

**Comment by aidanholm** [comment]
Implementation problems so far:
- No way to have GTK's homogenous children ignore non-expanded children. This means that it'll be necessary to have two separate tab boxes: one for pinned tabs, the other for regular tabs.
- It doesn't seem possible to wrap children of a box widget, which would be nice when using vertical tabs. It would probably be necessary to wrap the GtkFlowBox widget

**Comment by aidanholm** [comment]
I'm going to postpone this for now, as I'm more interested in working on a settings UI, and this is going to take a while. If anyone wants to take this up, I'm happy to answer questions.
